version: "3.7"
services:
  schnupf-dock:
    build:
      context: .
      network: host
    container_name: schnupf-dock
    volumes:
      - "${PWD}/spruechli.db:/app/spruechli.db:rw"
    ports:
      - "8001:8000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 1m
      timeout: 2s
      retries: 3
      start_period: 5s
